version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
    volumes:
      - .:/app
    restart: always
