# Generated by Django 5.0.4 on 2024-05-01 00:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("iso_alpha2", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=3)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(fields=("iso_alpha2",), name="unq_country_iso_alpha2"),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.Index(fields=["name"], name="idx_country_name"),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flights.country"),
        ),
        migrations.AddField(
            model_name="station",
            name="city",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="flights.city"),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(fields=("name", "country"), name="unq_city_name_country"),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(fields=("code",), name="unq_station_code"),
        ),
    ]
